receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  logging:
    loglevel: info
  prometheus:
    endpoint: ":8888"
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  batch:

service:
  telemetry:
    metrics:
      address: ":8889"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, logging]